CREATE DATABASE ts_api_users;
CREATE TABLE ts_api_users.users (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    dni VARCHAR(15) NOT NULL,
    names VARCHAR(255) NOT NULL,
    address TEXT NULL,
    phone VARCHAR(10) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    status INT(1) NOT NULL DEFAULT 0
);
DESCRIBE ts_api_users.users;